### ISSUE TITLE
App crashes due to AccountKitConfiguration Class not found while unmarshalling for android

### ISSUE THREAD

**Issue by kdinesh678** [Mhusain/FacebookAccountKit#8]
E/Parcel: Class not found when unmarshalling: com.facebook.accountkit.ui.AccountKitConfiguration
                                         java.lang.ClassNotFoundException: com.facebook.accountkit.ui.AccountKitConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2386)
                                             at android.os.Parcel.readParcelable(Parcel.java:2340)
                                            at android.os.Parcel.readValue(Parcel.java:2246)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2595)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:223)
                                             at android.os.BaseBundle.containsKey(BaseBundle.java:276)
                                             at android.content.Intent.hasExtra(Intent.java:5248)
                                             at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1451)
                                             at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1557)
                                             at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2754)
                                             at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:2152)
                                             at com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked(ActivityStackSupervisor.java:3382)
                                             at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1372)
                                             at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1181)
                                             at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:7135)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2746)
                                             at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:426)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.facebook.accountkit.ui.AccountKitConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2386) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2340) 
                                             at android.os.Parcel.readValue(Parcel.java:2246) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2595) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:223) 
                                             at android.os.BaseBundle.containsKey(BaseBundle.java:276) 
                                             at android.content.Intent.hasExtra(Intent.java:5248) 
                                             at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1451) 
                                             at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1557) 
                                             at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2754) 
                                             at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:2152) 
                                             at com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked(ActivityStackSupervisor.java:3382) 
                                             at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1372) 
                                             at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1181) 
                                             at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:7135) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2746) 
                                             at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:426) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Mhusain** [comment]
Sorry Guys,

I am busy in some other work. Thanks for your patience.

Can you please try to remove plugin, clean & build the project and then add the plugin again
